# Generated by Django 3.2.7 on 2022-03-22 06:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=3000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
