# Generated by Django 3.2.7 on 2022-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='User',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
